package enigma

const U string = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
const I string = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
const II string = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
const III string = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
const IV string = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
const V string = "VZBRGITYUPSDNHLXAWMJQOFECK"
const UKWA string = "EJMZALYXVBWFCRQUONTSPIKHGD"
const UKWB string = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
const UKWC string = "FVPJIAOYEDRZXWGCTKUQSBNMHL"
